all:
  children:
    masters:
      hosts:
        master1:
          ansible_host: 192.168.30.51
          ansible_port: 22
          ansible_user: root
          ansible_password: "WWSZ@1234"

  vars:
    # 容器镜像
    #image_name: hub.oepkgs.net/oedeploy/openeuler/aarch64/mindspore
    image_name: hub.oepkgs.net/oedeploy/openeuler/aarch64/intelligence_boom
    image_tag: 0.1.0-aarch64-300I-Duo-mindspore2.7-openeuler24.03-lts-sp2
    # 推理服务所在容器的名称
    container_name: openeuler_qwen2.5
    # 模型路径
    model_path: /home/models/Qwen2.5-14B-Instruct/
    # ray 开放的端口
    ray_port: 6379
    # 节点个数
    node_num: 1
    # 拉起服务前是否停止其他容器
    is_stop_other_container: 0
    # 推理服务端口
    llm_port: 8000
    # DP通信端口
    dp_port: 12570
    # ray集群使用的网卡
    ray_device: enp67s0f0np0
    # 模型权重类型
    model_type: safetensors
    # 后端(如果启动qwen2.5_vl,请设置为Native)
    backend_type: MindFormers
    # 跳过 ssh 校验（如需禁用此功能，请注释以下配置项）
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    # SSH连接复用参数，ControlMaster=auto启用连接复用，ControlPersist=60s保持连接60秒，ConnectTimeout=30设置连接超时30秒
    ansible_ssh_args: '-o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=30'
    # 启用Ansible管道加速，减少SSH连接次数
    ansible_pipelining: True
    # 启用SSH管道加速，提升文件传输效率
    ansible_ssh_pipelining: True
    # 设置并行执行的任务数
    ansible_forks: 10
